name = "telegram-openai-worker"
main = "src/worker.ts"
compatibility_date = "2024-09-02"
workers_dev = true

# account_id берётся из переменной окружения или передаётся флагом CLI в CI.

# Опциональная привязка KV для устойчивого хранения истории
# Перед деплоем создайте KV и свяжите его:
# wrangler kv:namespace create HISTORY
# затем добавьте binding ниже (или используйте через CLI/Action)
# [[kv_namespaces]]
# binding = "HISTORY"
# id = "<KV_NAMESPACE_ID>"


